MyTinyBlog/Web/MyTinyBlog.Web/Controllers/ManageController.cs
namespace MyTinyBlog.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.Owin;
    using Microsoft.Owin.Security;
    using MyTinyBlog.Web.ViewModels.Manage;

    [Authorize]
    public class ManageController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ManageController()
        {
        }

        public ManageController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Manage/Index
        public async Task<ActionResult> Index(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
                : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                : message == ManageMessageId.SetTwoFactorSuccess ? "Your two-factor authentication provider has been set."
                : message == ManageMessageId.Error ? "An error has occurred."
                : message == ManageMessageId.AddPhoneSuccess ? "Your phone number was added."
                : message == ManageMessageId.RemovePhoneSuccess ? "Your phone number was removed."
                : "";

            var userId = User.Identity.GetUserId();
            var model = new IndexViewModel
            {
                HasPassword = HasPassword(),
                PhoneNumber = await UserManager.GetPhoneNumberAsync(userId),
                TwoFactor = await UserManager.GetTwoFactorEnabledAsync(userId),
                Logins = await UserManager.GetLoginsAsync(userId),
                BrowserRemembered = await AuthenticationManager.TwoFactorBrowserRememberedAsync(userId)
            };
            return View(model);
        }

        //
        // POST: /Manage/RemoveLogin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveLogin(string loginProvider, string providerKey)
        {
            ManageMessageId? message;
            var result = await UserManager.RemoveLoginAsync(User.Identity.GetUserId(), new UserLoginInfo(loginProvider, providerKey));
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                message = ManageMessageId.RemoveLoginSuccess;
            }
            else
            {
                message = ManageMessageId.Error;
            }
            return RedirectToAction("ManageLogins", new { Message = message });
        }

        //
        // GET: /Manage/AddPhoneNumber
        public ActionResult AddPhoneNumber()
        {
            return View();
        }

        //
        // POST: /Manage/AddPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddPhoneNumber(AddPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            // Generate the token and send it
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), model.Number);
            if (UserManager.SmsService != null)
            {
                var message = new IdentityMessage
                {
                    Destination = model.Number,
                    Body = "Your security code is: " + code
                };
                await UserManager.SmsService.SendAsync(message);
            }
            return RedirectToAction("VerifyPhoneNumber", new { PhoneNumber = model.Number });
        }

        //
        // POST: /Manage/EnableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EnableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), true);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // POST: /Manage/DisableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DisableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), false);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // GET: /Manage/VerifyPhoneNumber
        public async Task<ActionResult> VerifyPhoneNumber(string phoneNumber)
        {
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), phoneNumber);
            // Send an SMS through the SMS provider to verify the phone number
            return phoneNumber == null ? View("Error") : View(new VerifyPhoneNumberViewModel { PhoneNumber = phoneNumber });
        }

        //
        // POST: /Manage/VerifyPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyPhoneNumber(VerifyPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePhoneNumberAsync(User.Identity.GetUserId(), model.PhoneNumber, model.Code);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                return RedirectToAction("Index", new { Message = ManageMessageId.AddPhoneSuccess });
            }
            // If we got this far, something failed, redisplay form
            ModelState.AddModelError("", "Failed to verify phone");
            return View(model);
        }

        //
        // POST: /Manage/RemovePhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemovePhoneNumber()
        {
            var result = await UserManager.SetPhoneNumberAsync(User.Identity.GetUserId(), null);
            if (!result.Succeeded)
            {
                return RedirectToAction("Index", new { Message = ManageMessageId.Error });
            }
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", new { Message = ManageMessageId.RemovePhoneSuccess });
        }

        //
        // GET: /Manage/ChangePassword
        public ActionResult ChangePassword()
        {
            return View();
        }

        //
        // POST: /Manage/ChangePassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = await UserManager.ChangePasswordAsync(User.Identity.GetUserId(), model.OldPassword, model.NewPassword);
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                return RedirectToAction("Index", new { Message = ManageMessageId.ChangePasswordSuccess });
            }
            AddErrors(result);
            return View(model);
        }

        //
        // GET: /Manage/SetPassword
        public ActionResult SetPassword()
        {
            return View();
        }

        //
        // POST: /Manage/SetPassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SetPassword(SetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await UserManager.AddPasswordAsync(User.Identity.GetUserId(), model.NewPassword);
                if (result.Succeeded)
                {
                    var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                    if (user != null)
                    {

MyTinyBlog/Web/MyTinyBlog.Web/Controllers/RolesController.cs
namespace MyTinyBlog.Web.Controllers
{
    using Microsoft.AspNet.Identity.EntityFramework;
    using Data.Models;
    using Services.Data;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using Microsoft.AspNet.Identity;
    using Data;

    public class RolesController : Controller
    {

        private readonly AdminService service;

        // GET: /Roles/Index
        public RolesController()
        {
            this.service = new AdminService();
        }

        public ActionResult Index()
        {
            IEnumerable<IdentityRole> roles = this.service.GetAllRoles();

            return View(roles);
        }

        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                this.service.CreateRole(collection["RoleName"]);


                ViewBag.ResultMessage = "Role created successfully !";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(string roleName)
        {
            this.service.DeleteRole(roleName);

            return RedirectToAction("Index");
        }

        //
        // GET: /Roles/Edit/5
        public ActionResult Edit(string roleName)
        {
            IdentityRole thisRole = this.service.GetRole(roleName);

            return View(thisRole);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IdentityRole role)
        {
            try
            {
                this.service.EditRole(role);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult ManageUserRoles()
        {
            // prepopulat roles for the view dropdown
            IEnumerable<SelectListItem> list = this.service.GetRolesForDropDown();
            ViewBag.Roles = list;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RoleAddToUser(string userName, string roleName)
        {
            ApplicationUser user = this.service.AddRoleToUser(userName);
            var um = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));

            var idResult = um.AddToRole(user.Id, roleName);

            ViewBag.ResultMessage = "Role created successfully !";

            // prepopulat roles for the view dropdown
            var list = this.service.GetRolesForDropDown();
            ViewBag.Roles = list;

            return View("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetRoles(string userName)
        {
            if (!string.IsNullOrWhiteSpace(userName))
            {
                ApplicationUser user = this.service.AddRoleToUser(userName);
                var um = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));

                ViewBag.RolesForThisUser = um.GetRoles(user.Id);

                // prepopulat roles for the view dropdown
                var list = this.service.GetRolesForDropDown();
                ViewBag.Roles = list;
            }

            return View("ManageUserRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteRoleForUser(string userName, string roleName)
        {
            var um = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            ApplicationUser user = this.service.AddRoleToUser(userName);

            if (um.IsInRole(user.Id, roleName))
            {
                um.RemoveFromRole(user.Id, roleName);
                ViewBag.ResultMessage = "Role removed from this user successfully !";
            }
            else
            {
                ViewBag.ResultMessage = "This user doesn't belong to selected role.";
            }
            // prepopulat roles for the view dropdown
            var list = this.service.GetRolesForDropDown();
            ViewBag.Roles = list;

            return View("ManageUserRoles");
        }
    }
}

MyTinyBlog/Web/MyTinyBlog.Web/Views/Admin/AddCategory.cshtml
@model MyTinyBlog.Data.Models.Category

<h2>Add Category</h2>
<section id="createCategoryForm">
    @using (Html.BeginForm("AddCategory", "Admin", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form_settings">
            <h4>Create new Category</h4>
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input class="submit" type="submit" value="Create" />
                </div>
            </div>
        </div>
    }
</section>

<div>
    @Html.ActionLink("Back to Manage", "Manage")
</div>

MyTinyBlog/Web/MyTinyBlog.Web/Views/Admin/AddPost.cshtml
@using MyTinyBlog.Web.MyTinyBlog.Web.ViewModels.Blog
@model CreateNewPostViewModel
@{
    ViewBag.Title = "Add Post";
}

<h2>@ViewBag.Title</h2>
<section id="createPostForm">
    @using (Html.BeginForm("AddPost", "Admin", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <div class="form_settings">
            @Html.AntiForgeryToken()
            <h4>Create new post</h4>
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ShortContent, new { @class = "col-md-2 control-label" })
                <div class="col-md-10" style="margin-left:130px">
                    @Html.TextAreaFor(m => m.ShortContent, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ShortContent, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "col-md-2 control-label" })
                <div class="col-md-10" style="margin-left:130px">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Content, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Category, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.DropDownList("Category", (IEnumerable<SelectListItem>)ViewBag.Categories, "Select ...", new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Tags, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Tags, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Tags, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input class="submit" type="submit" value="Create" />
                </div>
            </div>
        </div>

    }
</section>

<div>
    @Html.ActionLink("Back to Manage", "Manage")
</div>

MyTinyBlog/Web/MyTinyBlog.Web/Views/Admin/AddTag.cshtml
@model MyTinyBlog.Web.MyTinyBlog.Web.ViewModels.Blog.TagViewModel

<h2>Add Category</h2>
<section id="createTagForm">
    @using (Html.BeginForm("AddTag", "Admin", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form_settings">
            <h4>Create new Tag</h4>
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input class="submit" type="submit" value="Create" />
                </div>
            </div>
        </div>
    }
</section>

<div>
    @Html.ActionLink("Back to Manage", "Manage")
</div>

MyTinyBlog/Web/MyTinyBlog.Web/Views/Admin/Decline.cshtml
@using MyTinyBlog.Web.MyTinyBlog.Web.ViewModels.Blog
@model CategoryViewModel

<h2>Decline</h2>

<div>
    <h3>"@Html.DisplayFor(model => model.Name)" category cannot be deleted, because it is used in post(s)</h3>
</div>
<div>
    @Html.ActionLink("Back to Manage", "Manage")
</div>

MyTinyBlog/Web/MyTinyBlog.Web/Views/Admin/DeclineDeleteTag.cshtml
@using MyTinyBlog.Web.MyTinyBlog.Web.ViewModels.Blog
@model TagViewModel

<h2>Decline</h2>

<div>
    <h3>"@Html.DisplayFor(model => model.Name)" tag cannot be deleted, because it is used in post(s)</h3>
</div>
<div>
    @Html.ActionLink("Back to Manage", "Manage")
</div>

MyTinyBlog/Web/MyTinyBlog.Web/Views/Admin/Delete.cshtml
@using MyTinyBlog.Web.MyTinyBlog.Web.ViewModels.Blog
@model DeletePostViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div class="row" id="postDelete">
    <div class="form_settings">
        
        <div>
            <span>
                @Html.DisplayNameFor(model => model.Title) :
                @Html.DisplayFor(model => model.Title)
            </span>
        </div>
        <div>
            <span>
                @Html.DisplayNameFor(model => model.CreatedOn) :
                @Html.DisplayFor(model => model.CreatedOn)
            </span>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input class="submit" type="submit" value="Delete" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Back to Manage", "Manage")
                </div>
            </div>
        }
    </div>
</div>

MyTinyBlog/Web/MyTinyBlog.Web/Views/Admin/DeleteCategory.cshtml
@using MyTinyBlog.Web.MyTinyBlog.Web.ViewModels.Blog
@model CategoryViewModel

@{
    ViewBag.Title = "Delete category";
}

<h2>Delete category</h2>

<h3>Are you sure you want to delete this?</h3>
<div class="row" id="categoryDelete">
    <div class="form_settings">

        <div>
            <span>
                @Html.DisplayNameFor(model => model.Name) :
                @Html.DisplayFor(model => model.Name)
            </span>
        </div>
        <div>
            <span>
                @Html.DisplayNameFor(model => model.Description) :
                @Html.DisplayFor(model => model.Description)
            </span>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input class="submit" type="submit" value="Delete" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Back to Manage", "Manage")
                </div>
            </div>
        }
    </div>
</div>

MyTinyBlog/Web/MyTinyBlog.Web/Views/Admin/DeletePost.cshtml
@using MyTinyBlog.Web.MyTinyBlog.Web.ViewModels.Blog
@model DeletePostViewModel

@{
    ViewBag.Title = "Delete post";
}

<h2>Delete post</h2>

<h3>Are you sure you want to delete this?</h3>
<div class="row" id="postDelete">
    <div class="form_settings">
        
        <div>
            <span>
                @Html.DisplayNameFor(model => model.Title) :
                @Html.DisplayFor(model => model.Title)
            </span>
        </div>
        <div>
            <span>
                @Html.DisplayNameFor(model => model.CreatedOn) :
                @Html.DisplayFor(model => model.CreatedOn)
            </span>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input class="submit" type="submit" value="Delete" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Back to Manage", "Manage")
                </div>
            </div>
        }
    </div>
</div>

MyTinyBlog/Web/MyTinyBlog.Web/Views/Admin/DeleteTag.cshtml
@using MyTinyBlog.Web.MyTinyBlog.Web.ViewModels.Blog
@model TagViewModel

@{
    ViewBag.Title = "DeleteTag";
}

<h2>Delete tag</h2>

<h3>Are you sure you want to delete this?</h3>
<div class="row" id="tagDelete">
    <div class="form_settings">

        <div>
            <span>
                @Html.DisplayNameFor(model => model.Name) :
                @Html.DisplayFor(model => model.Name)
            </span>
        </div>
        <div>
            <span>
                @Html.DisplayNameFor(model => model.Description) :
                @Html.DisplayFor(model => model.Description)
            </span>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input class="submit" type="submit" value="Delete" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Back to Manage", "Manage")
                </div>
            </div>
        }
    </div>
</div>

MyTinyBlog/Web/MyTinyBlog.Web/Views/Admin/Manage.cshtml
@using MyTinyBlog.Web.MyTinyBlog.Web.ViewModels.Blog
@model ManageViewModel
<h2>Manage</h2>

<div>
    <p>
        @Html.ActionLink("Manage User Roles", "ManageUserRoles", "Roles")
    </p>
</div>

<div>
    <p>
        @Html.ActionLink("Create new Post", "AddPost", "Admin")
    </p>
</div>

<div>
    <p>
        @Html.ActionLink("Create new Category", "AddCategory", "Admin")
    </p>
</div>

<div>
    <p>
        @Html.ActionLink("Create new Tag", "AddTag", "Admin")
    </p>
</div>

<table>
    <tr>
        <th>Post title</th>
        <th>Created</th>
        <th>Details</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach (var item in Model.Posts)
    {
        <tr>
            <td>@Html.DisplayFor(model => item.Title)</td>
            <td>@Html.DisplayFor(model => item.CreatedOn)</td>
            <td>
                @Html.ActionLink("Go", "post", "blog",
            new
            {
                year = item.CreatedOn.Year,
                month = item.CreatedOn.Month,
                day = item.CreatedOn.Day,
                title = item.UrlSlug
            },
            new { title = "Go" })
            </td>
            <td>@Html.ActionLink("Edit", "EditPost", new { id = item.Id })</td>
            <td>@Html.ActionLink("Delete", "DeletePost", new { id = item.Id })</td> 
        </tr>
    }
</table>

<table>
    <tr>
        <th>Category name</th>
        <th>Description</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach (var item in Model.Categories)
    {
        <tr>
            <td>@Html.DisplayFor(model => item.Name)</td>
            <td>@Html.DisplayFor(model => item.Description)</td>
            <td>@Html.ActionLink("Edit", "EditCategory", new { id = item.Id })</td>
            <td>@Html.ActionLink("Delete", "DeleteCategory", new { id = item.Id })</td>
        </tr>
    }
</table>

<table>
    <tr>
        <th>Tag name</th>
        <th>Description</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach (var item in Model.Tags)
    {
        <tr>
            <td>@Html.DisplayFor(model => item.Name)</td>
            <td>@Html.DisplayFor(model => item.Description)</td>
            <td>@Html.ActionLink("Edit", "EditTag", new { id = item.Id })</td>
            <td>@Html.ActionLink("Delete", "DeleteTag", new { id = item.Id })</td>
        </tr>
    }
</table>